### ISSUE TITLE
npm start: Module not found error

### ISSUE THREAD

**Issue by riosv** [woodenconsulting/react-js-diagrams#4] opened 2017-04-10 01:06 UTC
Hi, I'm getting the following error after running `npm start`. I've been trying to figure it out but I can't find the issue. I'm on Ubuntu.

```
ERROR in ./demos/demo4/components/Diagram.js
Module not found: Error: Can't resolve './engine' in '/home/victor/front-end/react-js-diagrams/demos/demo4/components'
 @ ./demos/demo4/components/Diagram.js 18:0-41
 @ ./demos/demo4/demo4.js
 @ ./demos/demo4/index.js
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./demos/demo4/index.js
webpack: Failed to compile.
```
Here is the list of installed packages after running `npm install`:
```
$npm list --depth=0
react-js-diagrams@3.0.3 /home/victor/front-end/react-js-diagrams
├── babel-cli@6.24.0
├── babel-core@6.24.0
├── babel-loader@6.4.1
├── babel-plugin-add-module-exports@0.2.1
├── babel-plugin-transform-decorators-legacy@1.3.4
├── babel-plugin-transform-runtime@6.23.0
├── babel-preset-es2015@6.24.0
├── babel-preset-es2016@6.22.0
├── babel-preset-es2017@6.22.0
├── babel-preset-react@6.23.0
├── babel-preset-stage-0@6.22.0
├── babel-runtime@6.23.0
├── cross-env@4.0.0
├── css-loader@0.26.1
├── express@4.15.2
├── lodash@4.17.4
├── node-sass@4.5.0
├── react@15.5.3
├── react-dnd@2.3.0
├── react-dnd-html5-backend@2.3.0
├── react-dom@15.5.3
├── react-hot-loader@3.0.0-beta.6
├── react-redux@5.0.4
├── redux@3.6.0
├── redux-logger@2.10.2
├── redux-undo@0.6.1
├── sass-loader@6.0.0
├── source-map-loader@0.1.6
├── style-loader@0.13.1
├── webpack@2.3.3
├── webpack-dev-middleware@1.10.1
└── webpack-hot-middleware@2.18.0
```

Thanks

**Comment by woodenconsulting** [comment] 2017-04-10 23:01
@riosv This issue was caused by a bad import in the demo and is fixed in version `3.0.4`. If you're still having issues please let me know and I'll reopen.

**Closed as completed by woodenconsulting** 2017-04-10 23:01 UTC
